lib                := openvpn_plugin_ssl
#libname            := $(lib)-$(PACKAGEVERSION)
libname            := $(lib)
always             += $(if $(CONFIG_MODULES),$(libname).$(so),)

obj-m := $(libname).o
$(libname)-objs := plugin.o

plugin-ssl-dirs := mem net crypto aaa sys arch/$(SRCARCH)
plugin-ssl-objs := $(patsubst %,%/built-in.o, $(plugin-ssl-dirs)) \
                   modules/openvpn/$(libname).o
plugin-ssl-libs := $(patsubst %,%/lib.a, $(libs-y))
plugin-ssl-all  := $(plugin-ssl-objs) $(plugin-ssl-libs) $(KBUILD_LIBS)

$(obj)/$(libname).$(so): $(plugin-ssl-objs) $(plugin-ssl-libs)
	$(call if_changed,$(libname).$(so))

quiet_cmd_$(libname).$(so) = LD [M]  $@
	cmd_$(libname).$(so) = $(CC) $(LDFLAGS) $(SHLIB_LDFLAGS) -o $@ \
                                     $(plugin-ssl-all)

PHONY += $(plugin-ssl-dirs)
$(plugin-ssl-dirs): scripts_basic
	$(Q)$(MAKE) $(build)=$@
clean-files  += $(libname).$(so) $(libname).jar
