lib                   := aaa
libname               := lib$(lib)-$(PACKAGEVERSION)

always                += $(if $(CONFIG_MODULES),$(libname).$(so),)
always                += $(if $(JDK_HOME),$(libname).jar,)

obj-y                 += acc.o env.o cnf.o api.o 
obj-$(CONFIG_JNI)     += built-jni.o

ccflags-$(CONFIG_JNI) += -I$(JDK_HOME)/include -I$(JDK_HOME)/include/$(PLATFORM)
ccflags-$(CONFIG_JNI) += -DBUILD_JNI=1

#swflags              := -debug-module 1
swopt                 := 
swopt4j               := -package com.openaaa -I$(src) -I./java -java

libaaa-dirs           := mem net crypto lib/aaa sys/$(PLATFORM)
libaaa-objs           := $(patsubst %,%/built-in.o, $(libaaa-dirs))
libaaa-libs           := $(patsubst %,%/lib.a, $(libs-y))
libaaa-all            := $(libaaa-objs) $(libaaa-libs) $(KBUILD_LIBS)

$(obj)/$(libname).$(so): $(libaaa-objs) $(libaaa-libs)
	$(call if_changed,$(libname).$(so))

quiet_cmd_$(libname).$(so) = LD [M]  $@
	cmd_$(libname).$(so) = $(CC) $(LDFLAGS) $(SHLIB_LDFLAGS) -o $@ \
	                             $(libaaa-all)

PHONY += $(libaaa-dirs)
$(libaaa-dirs): scripts_basic
	$(Q)$(MAKE) $(build)=$@
clean-files  += $(libname).$(so) $(libname).jar

$(obj)/$(libname).jar: $(obj)/built-jni.c
	$(call if_changed,$(libname).jar)

quiet_cmd_$(libname).jar = JR      $@
	cmd_$(libname).jar = $(JAR) cf $(obj)/$(libname).jar \
	$(subst $(obj)/,-C $(obj) , $(wildcard $(obj)/com/openaaa/*.class))

$(obj)/Test.java: $(KBUILD_SRC)/$(src)/java/Test.java
	@cp $(KBUILD_SRC)/$(src)/java/Test.java $(obj)/Test.java

$(obj)/built-jni.c: $(src)/java/lib.i $(obj)/Test.java
	@swig $(swopt4j) -outdir $(obj)/ -o $@ $<
	@$(JAVAC) $(obj)/*.java -d $(obj)

$(obj)/python.c: $(src)/python/lib.i
	@swig $(swopt4py) -I$(s) -python -outdir $(obj)/ -o $@ $<
