lib                := mod_authnz_ssl
#libname            := $(lib)-$(PACKAGEVERSION)
libname            := $(lib)
always             += $(if $(CONFIG_MODULES),$(libname).$(so),)

obj-m := $(libname).o
$(libname)-objs := mod_openaaa.o ssl.o socache.o

ccflags-y := -Icrypto/abi -I/usr/include/apr-1 -I/opt/codeit/openssl111/include -Wno-unused-variable -Wno-unused-function

libaaa-http-dirs := mem net crypto aaa sys arch/$(SRCARCH)
libaaa-http-objs := $(patsubst %,%/built-in.o, $(libaaa-http-dirs)) modules/apache2/$(libname).o 
libaaa-http-libs := $(patsubst %,%/lib.a, $(libs-y))
libaaa-http-all  := $(libaaa-http-objs) $(libaaa-http-libs) $(KBUILD_LIBS)

$(obj)/$(libname).$(so): $(libaaa-http-objs) $(libaaa-http-libs)
	$(call if_changed,$(libname).$(so))

quiet_cmd_$(libname).$(so) = LD [M]  $@
	cmd_$(libname).$(so) = $(CC) $(LDFLAGS) $(SHLIB_LDFLAGS) -o $@ \
                                     $(libaaa-http-all)

PHONY += $(libaaa-http-dirs)
$(libaaa-http-dirs): scripts_basic
	$(Q)$(MAKE) $(build)=$@
clean-files  += $(libname).$(so) $(libname).jar
