
obj-y += $(PLATFORM)/ unix/ copt/
#obj-y += plt/
obj-y += exit.o units.o irq.o pid.o sock.o attr.o timestamp.o merge.o
obj-y += log/out.o
obj-$(CONFIG_DEBUG_LIST) += list.o

ifndef CONFIG_ARM
obj-y += mpm.o
endif

CFLAGS_mpm.o += -Wno-unused-value -Wno-unused-function 
CFLAGS_mpm.o += -Wno-comment -Wno-parentheses 


