
obj-y += $(PLATFORM)/ unix/ plt/ copt/
obj-y += exit.o units.o log.o irq.o mpm.o pid.o
obj-$(CONFIG_DEBUG_LIST) += list.o

CFLAGS_mpm.o += -Wno-unused-value -Wno-unused-function 
CFLAGS_mpm.o += -Wno-comment -Wno-parentheses 


