#!/bin/sh -k
args=$*
case "$args" in
  -m64)
    printf "64BIT !"
    ;;
esac
#-qsuppress=CCN4108 -qsuppress=CCN4105
S390_CFLAGS="-qlanglvl=gnu_varargmacros -D_XOPEN_SOURCE_EXTENDED=1 -DBENDIAN=1 -Daligned=__aligned__ -DNI_MAXHOST=1025 -DNI_MAXSERV=32 -DNO_INTTYPES_H -D__bool_=1 -qkeyword=typeof -Dinline=__inline__ -Dalloca=__alloca -qkeyword=typeof -D__typeof__=typeof -qsuppress=1506-224 -qsuppress=1506-068 -qsuppress=1506-280 -qsuppress=1506-196 -D_LARGE_TIME_API "
S390_TARGET="c99"
opts=""
lopts=""
temp2=""
mkdeps=""
nospacearg=" "
os390x=""

for arg in $* ; do
  case $arg in
    --version) 
      cc_version=`c99 c99 -qversion 2>&1 | grep "z/OS V" | sed 's/ \{1,\}/ /g' | head -n1`
      printf "$cc_version\n"
      exit 
      ;;
    -x\ c)
    exit 0
    ;;
    -print-file-name*)
    ;;
    -m31)
    ;;
    -m64*)
    lopts="$lopts -q64"
    ;;
    -D"KBUILD_STR(s)=#s") ;;
    -Wmissing-prototypes) ;;
    -Wall) ;;
    -fno-strict-aliasing) ;;
    -Wundef) ;;
    -mno-packed-stack) ;;
    -std=gnu89) opts="$opts -qlanglvl=extc89" ;;
    -std=gnu99) opts="$opts -qlanglvl=extc99" ;;
#    -std=gnu1x) opts="$opts -qlanglvl=extc1x" ;;
    -std=gnu1x) opts="$opts -qlanglvl=extc99" ;;
    -std=gnu11) opts="$opts -qlanglvl=extended1y" ;;
    -include) 
     temp2=$(echo "$arg" | sed -e 's/-include/-qinclude=/')
     opts="$opts $temp2"
     nospacearg=""
    ;;
    -fomit-frame-pointer) ;;
    -Wno-format-security) ;;
    -Wno-char-subscripts) ;;
    -Wstrict-prototypes) ;;
    -Wno-unused-value) ;;
    -Wno-unused-function) ;;
    -Wno-comment) ;; 
    -Wno-parentheses) ;;
    -print-file-name) ;;
    -dumpmachine)
      printf "aix\n"
      exit
      ;;
    -L*) lopts="$lopts $arg" ;;
    -print-file-name) ;;
    -Wp,-MD*)
     temp2=$(echo "$arg" | sed -e 's/-Wp,-MD,/-MF /')
     opts="$opts $temp2"
     mkdeps="y"
     ;;
    *) 
#    temp2=$(echo "$arg" | sed -e 's/-Wp,-MD,[^[:space:]]*[:space:].d//')
    opts="$opts$nospacearg$arg" 
    nospacearg=" "
    ;;
  esac
done

if [ ! -z "$mkdeps" ]; then
  S390_CFLAGS="-qmakedep=gcc -qlanglvl=extended -I../sys/os390 $S390_CFLAGS"
fi

c99 $S390_CFLAGS $os390x $lopts $opts 
