#!/bin/bash
PHASH=$(git rev-parse --short HEAD)

VERSION="$(git describe --abbrev=0 --tags).$(git rev-parse --short HEAD)"
transform="s,^\.,openaaa-$VERSION,"
tar --exclude='.git*' --exclude='obj*' --transform $transform \
	-czf $HOME/rpmbuild/SOURCES/openaaa-$VERSION.tar.gz .

#--transform 's,^openaaa,openaaa-${VERSION},' 
rpmbuild --define "_builddir $PWD/obj" \
         --define "_version $VERSION" -vv -bb rpm/openaaa.spec
