#!/bin/sh -k
# -DNO_INTPTR_T
S390_CFLAGS="-D_XOPEN_SOURCE_EXTENDED=1 -DBENDIAN=1 -Daligned=__aligned__ -DNI_MAXHOST=1025 -DNI_MAXSERV=32 -DPATH_MAX=1024 -DNO_SYS_POLL_H -DNO_INTTYPES_H"
S390_TARGET="c99"

# std mapping
# -std=gnu89 -qlanglvl=extc89
# -std=gnu89 -qlanglvl=extc99

opts=""
lopts=""
temp2=""
mkdeps=""

for arg in $* ; do
  case $arg in
    --version) 
      cc_version=`c99 c99 -qversion 2>&1 | grep "z/OS V" | sed 's/ \{1,\}/ /g' | head -n1`
      printf "$cc_version\n"
      exit 
      ;;
    -Wmissing-prototypes) ;;
    -Wall) ;;
    -std=gnu89) opts="$opts -qlanglvl=extc89" ;;
    -std=gnu99) opts="$opts -qlanglvl=extc99" ;;
    -include) 
     temp2=$(echo "$arg" | sed -e 's/-include/-qinclude/')
     opts="$opts $temp2"
    ;;
    -fomit-frame-pointer) ;;
    -Wno-format-security) ;;
    -Wno-char-subscripts) ;;
    -Wstrict-prototypes) ;;
    -print-file-name) ;;
    -dumpmachine)
      printf "s390\n"
      exit
      ;;
    -L*) lopts="$lopts $arg" ;;
    -print-file-name) ;;
    -Wp,-MD*)
     temp2=$(echo "$arg" | sed -e 's/-Wp,-MD,/-MF /')
     opts="$opts $temp2"
     mkdeps="y"
     ;;
    *) 
#    temp2=$(echo "$arg" | sed -e 's/-Wp,-MD,[^[:space:]]*[:space:].d//')
    opts="$opts $arg" ;;
  esac
done

if [ ! -z "$mkdeps" ]; then
  S390_CFLAGS="-qmakedep=gcc $S390_CFLAGS"
fi

printf "c99 $S390_CFLAGS $lopts $opts\n"

c99 $S390_CFLAGS $lopts $opts
