lib                := pkcs11
libname            := $(lib)-$(PACKAGEVERSION)
always             += $(if $(CONFIG_MODULES),$(libname).$(so),)

obj-m := $(libname).o
$(libname)-objs := pkcs11.o



#swflags           := -debug-module 1

lib$(lib)-dirs := mem net crypto lib/aaa sys/unix sys/$(PLATFORM) arch/$(SRCARCH)
lib$(lib)-objs := $(patsubst %,%/built-in.o, $(lib$(lib)-dirs)) \
                      modules/pkcs11/$(libname).o

lib$(lib)-libs := $(patsubst %,%/lib.a, $(libs-y))
lib$(lib)-all  := $(lib$(lib)-objs) $(lib$(lib)-libs) $(KBUILD_LIBS)

$(obj)/$(libname).$(so): $(lib$(lib)-objs) $(lib$(lib)-libs)
	$(call if_changed,$(libname).$(so))

quiet_cmd_$(libname).$(so) = LD [M]  $@
	cmd_$(libname).$(so) = $(CC) $(LDFLAGS) $(SHLIB_LDFLAGS) -o $@ \
	                             $(lib$(lib)-all)

PHONY += $(lib$(lib)-dirs)
$(lib$(lib)-dirs): scripts_basic
	$(Q)$(MAKE) $(build)=$@
clean-files  += $(libname).$(so) $(libname).jar


