testprogs-y := aaa
LIBS_aaa = aaa/built-in.o

# lib ev warning cleanup
CFLAGS_server.o += -Wno-unused-value -Wno-unused-function 
CFLAGS_server.o += -Wno-comment -Wno-parentheses 

lib                   := aaa
libname               := lib$(lib)-$(PACKAGEVERSION)

always                += $(libname).a
always                += $(if $(CONFIG_MODULES),$(libname).$(so),)
always                += $(if $(JDK_HOME),$(libname).jar,)

obj-y                 += acc.o env.o cnf.o api.o proto.o
obj-$(CONFIG_LINUX)   += server.o
obj-$(CONFIG_JNI)     += built-jni.o

ccflags-$(CONFIG_JNI) += -I$(JDK_HOME)/include -I$(JDK_HOME)/include/$(PLATFORM)
ccflags-$(CONFIG_JNI) += -DBUILD_JNI=1

#swflags              := -debug-module 1
swopt                 := 
swopt4j               := -package com.openaaa -I$(src) -I./java -java

libaaa-dirs           := sys mem net crypto aaa arch/$(SRCARCH)
libaaa-objs           := $(patsubst %,%/built-in.o, $(libaaa-dirs))
libaaa-libs           := $(patsubst %,%/lib.a, $(libs-y))
libaaa-all            := $(libaaa-objs) $(libaaa-libs) 

#$(KBUILD_LIBS)

$(obj)/$(libname).$(so): $(libaaa-objs) $(libaaa-libs)
	$(call if_changed,$(libname).$(so))

$(obj)/$(libname).a: $(libaaa-objs) $(libaaa-libs)
	$(call if_changed,$(libname).a)

quiet_cmd_$(libname).$(so) = LD [M]  $@
	cmd_$(libname).$(so) = $(CC) $(LDFLAGS) $(SHLIB_LDFLAGS) -o $@ \
	                             $(libaaa-all)
quiet_cmd_$(libname).a = AR      $@
	cmd_$(libname).a = $(AR) ar cr $@ $(libaaa-all)


PHONY += $(libaaa-dirs)
$(libaaa-dirs): scripts_basic
	$(Q)$(MAKE) $(build)=$@
clean-files  += $(libname).$(so) $(libname).jar

$(obj)/$(libname).jar: $(obj)/built-jni.c
	$(call if_changed,$(libname).jar)

quiet_cmd_$(libname).jar = JR      $@
	cmd_$(libname).jar = $(JAR) cmvf $(obj)/META-INF/MANIFEST.MF $(obj)/$(libname).jar \
	$(subst $(obj)/com/openaaa/, -C aaa/com/openaaa , $(wildcard $(obj)/com/openaaa/*.class))

$(obj)/Test.java: $(KBUILD_SRC)/$(src)/java/Test.java
	@cp -R $(KBUILD_SRC)/$(src)/java/META-INF $(obj)/
	@cp $(KBUILD_SRC)/$(src)/java/Test.java $(obj)/Test.java

$(obj)/built-jni.c: $(src)/java/lib.i $(obj)/Test.java
	@swig $(swopt4j) -outdir $(obj)/ -o $@ $<
	@$(JAVAC) $(obj)/*.java -d $(obj)

$(obj)/python.c: $(src)/python/lib.i
	@swig $(swopt4py) -I$(s) -python -outdir $(obj)/ -o $@ $<
